Feature bag identificaties
VNG-Realisatie/Haal-Centraal-BRP-bevragen pull request #1352
Opened 2022-10-20 08:59 UTC by fsamwel

In de BRP-V komt het (nog) voor dat er incorrecte BAG-identificaties worden toegevoegd. Deze bestaan dan niet uit exact 16 cijfers. RvIG meldt dit aan de betreffende gemeenten om te corrigeren en dit gebeurt ook.

Op dit moment levert de API dan deze identificaties. Bijvoorbeeld:
```
            "verblijfplaats": {
                "type": "Adres",
                "adresseerbaarObjectIdentificatie": "363010000123456 ",
                "nummeraanduidingIdentificatie": "363200000123456 "
            }
```

Dit antwoord voldoet niet aan de API specificaties en mag dus niet gestuurd worden.

Ik heb een gba-dev feature gemaakt die beschrijft en test dat in dit geval de BAG identificatie niet geleverd mag worden.

2022-10-21 08:58 UTC, JohanBoer requested changes

2022-10-21 08:58 UTC, JohanBoer commented on features/gba-dev/bag-identificatie.feature
> +@gba
De @gba tag is niet meer nodig

2022-10-21 08:58 UTC, JohanBoer commented on features/gba-dev/bag-identificatie.feature
> +Functionaliteit: BAG-identificaties met waarde die niet voldoet aan specificaties moet niet geleverd worden
Zin even ombouwen naar meervoud. (BAF-identificaties met waarden die niet voldoen aan de specificaties moeten niet geleverd worden.)

2022-10-21 08:58 UTC, JohanBoer commented on features/gba-dev/bag-identificatie.feature
> +      | type     | Adres  |
De gba api levert geen type.

2022-10-21 08:58 UTC, JohanBoer commented on features/gba-dev/bag-identificatie.feature
> +      | type                             | Adres            |
Ook hier: gba api levert geen type

2022-10-21 09:15 UTC, fsamwel commented on features/gba-dev/bag-identificatie.feature
> +Functionaliteit: BAG-identificaties met waarde die niet voldoet aan specificaties moet niet geleverd worden
omgebouwd naar enkelvoud

2022-10-21 09:15 UTC, fsamwel commented on features/gba-dev/bag-identificatie.feature
> +@gba
verwijderd

2022-10-21 09:16 UTC, fsamwel commented on features/gba-dev/bag-identificatie.feature
> +      | type     | Adres  |
verwijderd

2022-10-21 09:16 UTC, fsamwel commented on features/gba-dev/bag-identificatie.feature
> +      | type                             | Adres            |
verwijderd

2022-10-21 10:35 UTC, JohanBoer approved these changes

2022-10-24 14:22 UTC, CathyDingemanse approved these changes

2022-10-26 10:00 UTC, melsk-r approved these changes

2022-10-26 12:42 UTC, merged

2022-11-02 08:14 UTC, CathyDingemanse commented
@fsamwel is dit alleen het geval bij deze BAG identificaties of is dit ook het geval bij andere waarden?