Update in_onderzoek.feature
VNG-Realisatie/Haal-Centraal-BRP-bevragen pull request #1461
Opened 2022-11-29 12:10 UTC by melsk-r

In de scenario's 'persoon heeft <in onderzoek> in onderzoek' en 'persoon heeft <groep> <in onderzoek> in onderzoek' ontbraken bij enkele voorbeelden velden.

2022-11-30 13:18 UTC, JohanBoer requested changes
1 aanpassing nodig. verder goed. Indien aanpassing gedaan mag deze wat mij betreft gemerged worden.

2022-12-01 09:05 UTC, melsk-r commented on features/in_onderzoek.feature
> +      | inOnderzoek.indicatieVestigingVanuitBuitenland | true         |
Maar zou het niet zo kunnen zijn dat het feit dat 'datum vestiging in Nederland' geen waarde heeft de reden is dat dit veld in onderzoek is (waardoor ook 'indicatieVestigingVanuitBuitenland' in onderzoek is)? 

Natuurlijk kan ik nog een scenario opnemen (en zal ik dat ook doen) waarbij dat veld wel een waarde heeft en ook in onderzoek is. In dat geval krijgt 'indicatieVestigingVanuitBuitenland' inderdaad de waarde true in de response.

2022-12-06 10:42 UTC, fsamwel commented on features/in_onderzoek.feature
> +      | inOnderzoek.indicatieVestigingVanuitBuitenland | true         |
het maakt inderdaad niet uit of het betreffende gegeven een waarde heeft. dus ook waneer er geen vestiging vanuit buitenland is, maar daar loopt wel onderzoek naar.

Nu is het een voorbeeld met expliciet in onderzoek zetten van de immigratiedatum, maar hetzelfde had gegolden bij onderzoek naar de hele migratie (081400) of de hele verblijfplaats (080000).

Maar het is wel beter om die datum wel op te nemen, anders test het impliciet twee functionaliteiten/rules. Beter/duidelijker om per scenario maar één ding te illustreren en andere complexiteiten erbuiten te houden.

Aan de andere kant is het puur vanuit testperspectief vaak wel interessant (ergens in een dev scenario) om juist ook de combinatie van soort regels ergens te toetsen. Dus als je zin heb kan je kijken of je die situatie toch nog ergens opneemt. Dan moet je m.i. in de titel van het scenario wel expliciet maken dat je die combinatie test, bijvoorbeeld "er is geen immigratie geregistreerd en er loopt onderzoek naar de immigratie"

2022-12-08 09:23 UTC, melsk-r commented on features/in_onderzoek.feature
> +      | inOnderzoek.indicatieVestigingVanuitBuitenland | true         |
Ik zal de datum opnemen zodat deze PR gemerged kan worden.
Ik maak dus geen scenario('s) om ook de combinatie van regels te testen. Niet omdat ik er geen zin in heb maar omdat het verstandig is deze PR te mergen zodat we verder kunnen met de geherordende in_onderzoek.feature en on_onderzoek-gba.feature.

2022-12-12 08:29 UTC, closed without merging

2022-12-12 08:30 UTC, melsk-r commented
Alle wijzigingen in deze PR worden ook afgedekt door PR #1491.