fix(fields-mapping-gba): verblijfplaats(Binnenland) mappings aangescherpt
VNG-Realisatie/Haal-Centraal-BRP-bevragen pull request #1492
Opened 2022-12-08 13:13 UTC by MelvLee

2022-12-12 08:33 UTC, KayodeBakker reviewed
Ik mis de volgende fields vertalingen:

- verblijfplaats.type (straat|locatiebeschrijving|land)
- verblijfplaatsBinnenland (deze mist datumAanvangAdreshouding)
- verblijfplaatsBinnenland.type (straat)
- verblijfplaatsBinnenland.verblijfadres.regel1 (straat)
   - Ik kan mij voorstellen dat regel2 en regel3 ook vergelijkbare situaties levert

2022-12-12 11:34 UTC, fsamwel commented
> verblijfplaatsBinnenland.verblijfadres.regel1

@KayodeBakker dit moet volgens mij een fout opleveren, omdat verblijfplaatsBinnenland.verblijfadres geen veld regel1 bevat.
Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/develop/features/bevragen/persoon/verblijfplaats/fields-alias-fout-cases.feature#L31

2022-12-12 11:37 UTC, fsamwel commented
> verblijfplaatsBinnenland.type (straat)

naast straat moet dit ook locatiebeschrijving geven

2022-12-12 11:37 UTC, fsamwel requested changes
zie opmerkingen @KayodeBakker over ontbrekende velden

2022-12-12 14:26 UTC, KayodeBakker reviewed
Ik heb de wijzigingen gezien, maar snap nog steeds dan niet het binnenlandsadres regel verhaal uit een eerdere comment.

2022-12-12 14:56 UTC, KayodeBakker commented
Ik heb tevens ook een issue met de volgende scenarios uit ook gba-dev/persoon.feature:

- Scenario: één of meerdere velden van een verblijfplaats buitenland wordt gevraagd met field pad 'verblijfplaatsBinnenland' # features\gba-dev\persoon.feature:276
- Scenario: één of meerdere velden van een verblijfplaats buitenland wordt gevraagd met field pad 'verblijfplaatsBinnenland.type' # features\gba-dev\persoon.feature:277
- Scenario: één of meerdere velden van een verblijfplaats buitenland wordt gevraagd met field pad 'verblijfplaatsBinnenland.datumVan' # features\gba-dev\persoon.feature:278
- Scenario: één of meerdere velden van een verblijfplaats buitenland wordt gevraagd met field pad 'verblijfplaatsBinnenland.datumVan,verblijfplaatsBinnenland.functieAdres' # features\gba-dev\persoon.feature:279
- Scenario: één of meerdere velden van een verblijfplaats buitenland wordt gevraagd met field pad 'verblijfplaatsBinnenland.verblijfadres' # features\gba-dev\persoon.feature:280
- Scenario: één of meerdere velden van een verblijfplaats buitenland wordt gevraagd met field pad 'verblijfplaatsBinnenland.datumVan,verblijfplaatsBinnenland.verblijfadres.huisnummer' # features\gba-dev\persoon.feature:281

De reden hiervoor is dat er een leeg persoon object (ofwel {} ) wordt verwacht. Echter de fields die gebruikt worden, worden direct vertaald tot verblijfplaats velden. Als deze velden niet geleverd kunnen worden dan dient uit eerdere afspraken de logische conclusie te zijn dat het een leeg verblijfplaats object is (ofwel { verblijfplaats: {} } ).
Ik ben niet willig om de code hier nogmaals voor te moeten gaan omzeilen aangezien we steeds meer bug kansen gaan veroorzaken op deze manier.

2022-12-13 07:48 UTC, melsk-r commented on features/gba-dev/fields-mapping-gba.csv
> +verblijfplaatsBinnenland.type|verblijfplaats.straat|verblijfplaats.locatiebeschrijving
Volgens mij klopt deze regel niet. De eerste '|' moet volgens mij een ',' zijn.

2022-12-13 10:41 UTC, MelvLee commented on features/gba-dev/fields-mapping-gba.csv
> +verblijfplaatsBinnenland.type|verblijfplaats.straat|verblijfplaats.locatiebeschrijving
aangepast

2022-12-14 08:45 UTC, merged