Correctie onbekendwaarde n.a.v. issue #1498
VNG-Realisatie/Haal-Centraal-BRP-bevragen pull request #1506
Opened 2022-12-14 15:38 UTC by JohanBoer

2022-12-15 10:47 UTC, fsamwel commented on features/gba-dev/onbekend_waardes_gba.feature
> +    | Europees kiesrecht (31.10)                       | 1        |
Waarom wordt in de Dan stap geen europeesKiesrecht.aanduiding verwacht?
Idem uitsluitingKiesrecht.uitgeslotenVanKiesrecht?

2022-12-15 10:50 UTC, fsamwel requested changes
Je hebt in de Gegeven stappen iets toegevoegd en niet bij de Dan stappen. Als dit staagt is het een bug!

2022-12-16 09:04 UTC, fsamwel commented on features/gba-dev/onbekend_waardes_gba.feature
> +    | Europees kiesrecht (31.10)                       | 1        |
ik zie het al, is niet gevraagd met fields

2022-12-16 09:22 UTC, JohanBoer commented
PR ingetrokken n.a.v. discussie dagstart 16-12. GBA-Api wordt aangepast. Logica die controleert dat datums alleen geleverd worden als de de aanduidingen bij kiesrecht gevuld zijn wordt uit de GBA-API verwijderd

2022-12-16 09:22 UTC, closed without merging