gba verblijfplaatsbeperkt fields scenario's
VNG-Realisatie/Haal-Centraal-BRP-bevragen pull request #1516
Opened 2022-12-21 07:49 UTC by MelvLee

2022-12-21 09:44 UTC, KayodeBakker requested changes
Bij meerdere scenarios wordt de fields 'verblijfplaats.type' gebruikt, echter de GBA kent geen type binnen verblijfplaats. Mocht dit een copy pasta fout zijn dan helder, maar mocht dit bewust zijn gedaan als vertaling van proxy field naar gba field dan twijfel ik of dit de juiste plek ervoor is.

2022-12-21 14:31 UTC, CathyDingemanse approved these changes
Volgens mij helemaal goed!

2022-12-21 14:44 UTC, MelvLee commented
> Bij meerdere scenarios wordt de fields 'verblijfplaats.type' gebruikt, echter de GBA kent geen type binnen verblijfplaats. Mocht dit een copy pasta fout zijn dan helder, maar mocht dit bewust zijn gedaan als vertaling van proxy field naar gba field dan twijfel ik of dit de juiste plek ervoor is.

Maar mappings voor verblijfplaats.type en verblijfplaatsBinnenland.type zijn terug te vinden in fields-mapping-gba.csv. Zie regel 62 en 81

2023-01-11 14:53 UTC, MelvLee commented
duplicaat van #1537

2023-01-11 14:53 UTC, closed without merging