Genderneutraal
VNG-Realisatie/Haal-Centraal-BRP-bevragen pull request #684
Opened 2020-10-16 06:55 UTC by fsamwel

- aanschrijving als geslachtsaanduiding is onbekend
- aanschrijving voor adellijke titel of predicaat wanneer geslachtsaanduiding gewijzigd is

Fixes #683

2020-10-16 12:27 UTC, KayodeBakker commented
Ik heb de volgende vragen en opmerkingen:

- _"Voor een persoon zonder adellijke titel of predicaat begint de briefaanhef met “Geachte mevrouw” (vrouw) of “Geachte heer” (man) of "Geachte " plus de voorletters (onbekend)"_
  - Het feit dat (vrouw), (man) en (onbekend) worden getoond in het boven genoemde stukje is puur illustratief toch? We gaan dat niet daadwerkelijk plaatsen in die aanschrijfwijze mag ik hopen? Mocht ik hier gelijk in hebben dan zou ik dit voorbeeld iets anders schrijven zodat het niet deze verwarring kan laten ontstaan.
- _" | Ridder                   | vrouw               | Hoogwelgeboren vrouwe |"_
  - Dit wordt genoemd in de aanhef feature, echter in de aanschrijfwijze wordt aangegeven dat een persoon met geslachtsaanduiding vrouw nooit een ridder kan zijn. Welke van de 2 is waar? Het is namelijk raar dat er wel een aanhef voor is maar niet een aanschrijfwijze. In beide gevallen worden personen met geslachtsaanduiding onbekend aangeschreven en krijgen een aanhef als een persoon zonder titel of predikaat.

Al met al zie ik geen rare dingen verder, echter gaat dit de bestaande spinnenweb code nog complexer maken dus duidelijk en eenvoudig te volgen, maar implementatie technisch wordt het nog even een uitdaginkje

2020-10-16 12:35 UTC, fsamwel commented
> "Voor een persoon zonder adellijke titel of predicaat begint de briefaanhef met “Geachte mevrouw” (vrouw) of “Geachte heer” (man) of "Geachte " plus de voorletters (onbekend)"
Het feit dat (vrouw), (man) en (onbekend) worden getoond in het boven genoemde stukje is puur illustratief toch? We gaan dat niet daadwerkelijk plaatsen in die aanschrijfwijze mag ik hopen? Mocht ik hier gelijk in hebben dan zou ik dit voorbeeld iets anders schrijven zodat het niet deze verwarring kan laten ontstaan.

Het geslacht tussen haakjes geeft aan bij welke geslachtsaanduiding welke tekst wordt toegevoegd. Je kan dit dus lezen als:
Als geslachtsaanduiding is gelijk aan "vrouw", dan wordt “Geachte mevrouw” toegevoegd
Als geslachtsaanduiding is gelijk aan "man", dan wordt “Geachte heer” toegevoegd
Als geslachtsaanduiding is gelijk aan "onbekend", dan wordt “Geachte” toegevoegd, plus de voorletters

2020-10-16 12:48 UTC, fsamwel commented
> Dit wordt genoemd in de aanhef feature, echter in de aanschrijfwijze wordt aangegeven dat een persoon met geslachtsaanduiding vrouw nooit een ridder kan zijn. Welke van de 2 is waar? Het is namelijk raar dat er wel een aanhef voor is maar niet een aanschrijfwijze.

Is inderdaad beetje raar, maar de reden dat ik bij aanschrijfwijze de vrouwelijke ridder niet opgenomen heb, is niet omdat er geen titel is, maar omdat we geen vrouwelijk equivalent kennen. Voor de aanhef kan ik wel een vrouwelijk equivalent bedenken.
@CathyDingemanse vindt jij dat dit opgelost moet worden? Zo ja hoe?

Bijvoorbeeld titel Ridder en geslachtsaanduiding vrouw:
1. Aanhef: "Hoogwelgeboren vrouwe", aanschrijfwijze: "M. van den Aedel", gebruikInLopendeTekst: "mevrouw Van den Aedel"
2. Aanhef: "Hoogwelgeboren vrouwe", aanschrijfwijze: "M. ridder van den Aedel", gebruikInLopendeTekst: "ridder van den Aedel"
3. Aanhef: "Geachte mevrouw Van den Aedel", aanschrijfwijze: "M. van den Aedel", gebruikInLopendeTekst: "mevrouw Van den Aedel"

2020-10-20 10:18 UTC, CathyDingemanse commented
Als er geen vrouwelijke equivalent is, is dat helaas niet anders. Ik ga voor jouw oorspronkelijke oplossing, dus:
1. Aanhef: "Hoogwelgeboren vrouwe", aanschrijfwijze: "M. van den Aedel", gebruikInLopendeTekst: "mevrouw Van den Aedel"

2020-10-20 10:55 UTC, CathyDingemanse commented on features/aanhef.feature
> -      | adellijkeTitel_predikaat | aanduidingNaamgebruik | aanschrijfwijze                             | aanhef                    |
Bij aanschrijfwijze komt er een attribuut bij: RegelVoorafgaandAanAanschrijfwijze met als description: deze regel moet als aparte regel boven de aanschrijfwijze worden geplaatst. Komt alleen voor bij personen met een adellijke titel of predicaat.  

website hoge raad van adel:
Wanneer de geadresseerde recht heeft op een predicaat, dan krijgt dit als eerste woord van de adressering een hoofdletter. Het gebruik van de woorden ‘De heer’ en ‘Mevrouw’ naast een titel of predikaat is dubbelop en daarom onjuist.

De adressering aan graven en burggraven luidt 'De hooggeboren heer', die  aan gravinnen en burggravinnen 'De hooggeboren vrouwe'. Een brief begint dan met 'Hooggeboren heer / vrouwe', gevolgd door een komma, een witregel en de briefinhoud:

De hooggeboren heer
A.B.C. graaf van Limburg Stirum
Voor de overige edellieden is de adressering 'De hoogwelgeboren heer / vrouwe' en de briefaanhef 'Hoogwelgeboren heer / vrouwe', gevolgd door een komma, een witregel en de briefinhoud:

De hoogwelgeboren vrouwe
A.B.C. barones van Dedem
De hoogwelgeboren heer
Jonkheer A.B.C. Verheyen.

2020-10-20 15:19 UTC, fsamwel commented
@CathyDingemanse @KayodeBakker ik heb regelVoorafgaandAanAanschrijfwijze toegevoegd en eerste predicaat in aanschrijfwijze begint met hoofdletter. 

Kunnen jullie nog even checken of het er nu goed in staat? Dan kan ik het mergen

2020-10-20 17:03 UTC, CathyDingemanse reviewed
Tjonge jonge wat een werk Frank.... en Kayo :-(.

2020-10-22 08:26 UTC, fsamwel commented on features/aanhef.feature
> +      | Jonkvrouw                | man                 | Eigen                 | Ja      | Geen                                           | Geachte heer Van Hoogh                 |
Dit is inderdaad een geval geslachtswijziging, waarbij wel de geslachtsaanduiding is gewijzigd, maar niet de adellijke titel. Het feature toont nu dat in dat geval de aanhef bij het predicaat wordt opgenomen in de variant van het nieuwe geslacht. Dus een persoon met predicaat "jonkvrouw", en geslacht "man" krijgt aanhef "Hoogwelgeboren heer".
Maar de regels voor het gebruik van het predicaat zijn nog steeds gebaseerd op het feitelijke predicaat. Een jonkvrouw met partner wordt niet meer aangesproken als jonkvrouw. Alleen een ongetrouwde vrouw kan jonkvrouw zijn. Een getrouwde jonkheer is nog wel jonkheer. Dit alles is alles behalve genderneutraal, maar zo is het gebruik/zijn de regels voor gebruik van het predicaat.
Jij stelt dus dat een jonkvrouw die trouwt, en daardoor niet meer als jonkvrouw wordt aangeschreven (in aanschrijfwijze of aanhef), en daarna door van geslacht te wijzigen haar/zijn predicaat weer mag gaan gebruiken?

2020-10-22 08:28 UTC, fsamwel commented on features/aanschrijfwijze.feature
> +  En betrokkene de geslachtsnaam van de echtgenoot/partner gebruikt zonder de eigen geslachtsnaam
alleen bij "P"

2020-10-22 08:34 UTC, CathyDingemanse commented on features/aanhef.feature
> +      | Jonkvrouw                | man                 | Eigen                 | Ja      | Geen                                           | Geachte heer Van Hoogh                 |
Ja inderdaad. Voor een jonkheer die een geslachtsverandering ondergaat geldt dat niet.

2020-10-22 08:37 UTC, fsamwel commented on features/aanhef.feature
>    Als betrokkene de geslachtsnaam van de echtgenoot/partner gebruikt zonder de eigen geslachtsnaam,
alleen "P"

2020-10-22 09:08 UTC, fsamwel commented on features/aanhef.feature
> +      | Jonkvrouw                | man                 | Eigen                 | Ja      | Geen                                           | Geachte heer Van Hoogh                 |
Hoe bedoel je dit "Voor een jonkheer die een geslachtsverandering ondergaat geldt dat niet."?

Een jonkheer trouwt en wordt dus aangeschreven als "jonkheer", ondergaat daarna geslachtswijziging tot vrouw. verliest zij daarmee haar predicaat in de aanschrijving als was ze altijd een jonkvrouw geweest? Of schrijven we haar aan als jonkvrouw/Hoogwelgeboren vrouwe, terwijl voor jonkvrouwen die als vrouw geboren zijn na het trouwen hun predicaat niet meer gebruikt wordt.

Ik heb de features nu beschreven vanuit de regels voor het geregistreerde predicaat, en alleen de getoonde aanhef aangepast op het geslacht. Maar wellicht is het beter dan ook de regels voor het toepassen van het predicaat te baseren op het geslacht, zodat het getoonde predicaat in lijn is met de regels voor dat predicaat. Een jonkheer die van geslacht verandert krijgt dan aanhef en aanschrijfwijze als was ze altijd al jonkvrouw geweest.
Mee eens?

2020-10-22 09:19 UTC, CathyDingemanse commented on features/aanhef.feature
> +      | Jonkvrouw                | man                 | Eigen                 | Ja      | Geen                                           | Geachte heer Van Hoogh                 |
Precies. Mee eens!

2020-10-22 12:37 UTC, KayodeBakker requested changes
Voor nu is het lastig om te zien of hier code technisch issues mee zullen zijn. Functioneel technisch zie ik geen grote issues echt meer.

Wat is meer wenselijk? Dat we wachten met de pull request afronden tot ik het compleet geïmplementeerd heb of dat we het afronden en als ik tegen issues aanloop dat ik die daarna meld?

2020-10-22 13:44 UTC, CathyDingemanse commented
> Voor nu is het lastig om te zien of hier code technisch issues mee zullen zijn. Functioneel technisch zie ik geen grote issues echt meer.
> 
> Wat is meer wenselijk? Dat we wachten met de pull request afronden tot ik het compleet geïmplementeerd heb of dat we het afronden en als ik tegen issues aanloop dat ik die daarna meld?

Zullen we het afronden als jij klaar bent? Dan pakken we evt. problemen gelijk mee.

2020-10-22 14:44 UTC, fsamwel commented
@KayodeBakker ik zie "KayodeBakker requested changes 2 hours ago" maar zie eigenlijk niet welke wijzigingen je precies verwacht. Ben ik zo scheel?

2020-10-26 10:32 UTC, KayodeBakker commented
@fsamwel Dit was expres gedaan omdat ik er vanuit ga dat als ik tijdens ontwikkeling tegen iets aanloop dat ik een opmerking plaats.

2020-10-28 09:49 UTC, KayodeBakker requested changes
Ik heb tijdens het ontwikkelen van deze drie features nogmaals goed gekeken en ik heb een aantal vraagjes en een aantal opmerkingen wat wellicht leidt naar een duidelijkere feature.

2020-10-28 13:06 UTC, fsamwel commented on features/aanhef.feature
> +  Wanneer geslachtsaanduiding is niet leeg of "onbekend", dan wordt het voorvoegsel van de eerste geslachtsnaam in de briefaanhef met een hoofdletter geschreven.
Als geslachtsaanduiding is onbekend, dan worden de voorletters toegevoegd. Voorvoegsel krijgt alleen een hoofdletter, wanneer deze helemaal vooraan in de naam staat ("mevrouw" en "de heer" tellen in deze context niet mee bij de naam):
- mevrouw Van Hier-tot Daar
- A.B.C. van Hier-tot Daar

Daarom komt deze regel ook alleen voor in de features voor aanhef en gebruikInLopendeTekst en niet in aanschrijfwijze, omdat in de laatste er altijd voorletters voor het voorvoegsel staan.

2020-10-28 13:07 UTC, fsamwel commented on features/aanhef.feature
> +  En de aanschijfwijze is ongelijk aan "E" - "Eigen"
dank je, staat er fout. corrigeer ik

2020-10-28 13:08 UTC, fsamwel commented on features/aanhef.feature
> +  En de aanschijfwijze is ongelijk aan "E" - "Eigen"
klopt. opgelost

2020-10-28 13:12 UTC, fsamwel commented on features/aanhef.feature
> +      | Jonkvrouw                | vrouw               | Partner voor eigen    | Ja      | Geen                                           | Geachte mevrouw Van der Veen           |
opgelost

2020-10-28 13:15 UTC, fsamwel commented on features/aanhef.feature
>    En de persoon wordt dan aangesproken met “Geachte mevrouw” of “Geachte heer” gevolgd door voorvoegsel en geslachtsnaam van de partner.
ik herformuleer dit

2020-10-28 13:17 UTC, fsamwel commented on features/aanhef.feature
> +      | Eigen                 | man                 | GA VV GN            | F. Groenen                | Geachte heer Groenen                   |
klopt

2020-10-28 13:19 UTC, fsamwel commented on features/aanhef.feature
> +      | Partner na eigen      | vrouw               | GA VV GN-VP GP      | F. Groenen-Groenink       | Geachte mevrouw Groenen-Groenink       |
pas ik aan

2020-10-28 13:36 UTC, fsamwel commented on features/aanhef.feature
> +      | Graaf                    | man                 | Partner               | F. van der Veen                             | Geachte heer Van der Veen |
Ik had hiervoor de aanschrijfwijze opgenomen. Overweging is dat opnemen van kolommen voor voorvoegsels en geslachtsnamen van de personen en de partners de tabellen zo breed maken dat de relevante kolommen niet meer tegelijk in beeld zijn. Beetje een compromis. 

Ik heb een beetje geprobeerd te helpen daarbij door alle mensen met een adellijke titel "van den Aedel" te noemen, of "van Roodt de Wit Blaauw" en alle mensen met een predikaat "van Hoogh".

De mensen zonder titel of predicaat heten van Velzen, van der Veen, Groenen of Groenink.

2020-10-28 13:41 UTC, fsamwel commented on features/aanhef.feature
> +  | Prins, Prinses           | onbekend            | Hoogheid              |
we weten of het een prins of prinses is uit de waarde in adellijkeTitel_predikaat. Maar bij het opnemen in de naamvelden kunnen we dat niet correct doen, want dit zijn geen genderneutrale benamingen.
Wanneer dus een persoon de moeite heeft genomen niet meer geregistreerd te zijn als vrouw, nemen we aan dat de vrouwelijke titel "prinses" ook niet meer gewenst is. Dus wordt die niet opgenomen in de aanschrijfwijze en gebruikInLopendeTekst.
Maar de aanhef "Hoogheid" is genderneutraal. Daarom kunnen we die wel gebruiken, ongeacht de geslachtsaanduiding (incl. onbekend).

2020-11-02 15:09 UTC, merged