Develop
VNG-Realisatie/Haal-Centraal-BRP-bevragen pull request #776
Opened 2021-01-12 16:52 UTC by JohanBoer

Ik heb n.a.v. tips van Melvin eerst de master gemerged naar de develop (lokaal) en de code en test-wijzigingen verwijderd in mijn lokale "develop". Die heb ik vervolgens via mijn fork naar de "develop" op deze repo gemerged. 

Volgens mij gaat het nu goed, maar ik krijg volgen mij nu een paar commits mee die al op de master zijn doorgevoerd. (Bv die van 2 december van Melvin) 

Ik kan automatisch mergen, maar stel het op prijs als jullie een (korte) check doen om zeker te weten dat ik hier geen gekke dingen heb gedaan.

2021-01-12 17:16 UTC, fsamwel commented
wat is de bedoeling hiervan? Ga je een release v1.2 maken?

2021-01-13 10:09 UTC, JohanBoer commented
> wat is de bedoeling hiervan? Ga je een release v1.2 maken?

Ja, dat hebben we volgens mij afgesproken n.a.v. #746 en [hier](https://github.com/VNG-Realisatie/Haal-Centraal/issues/34)

2021-01-13 10:46 UTC, JohanBoer commented
Let op ook #777 meenemen in v1.2.0

2021-01-14 11:14 UTC, fsamwel requested changes
De wijzigingen aan de readme kloppen niet. Je zet hier weer een oude versie van de readme terug.

2021-01-14 11:18 UTC, fsamwel commented
ook definition of done, definition of ready en product vision waren bewust verwijderd, maar worden met deze pull request weer toegevoegd.

2021-01-14 15:26 UTC, closed without merging