Update getting-started.md
VNG-Realisatie/Haal-Centraal-BRP-bevragen pull request #884
Opened 2022-01-05 09:44 UTC by melsk-r

Aanpassingen n.a.v. het verwijderen van de gegenereerde client code.

2022-01-10 15:01 UTC, fsamwel approved these changes

2022-01-10 16:21 UTC, CathyDingemanse requested changes

2022-01-10 16:21 UTC, CathyDingemanse commented on docs/getting-started.md
> +Client code kan worden gegenereerd vanuit de "[genereervariant](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/specificatie/genereervariant/openapi.yaml){:target="_blank" re
Je kunt client code genereren met.... 
Een overzicht van code generatoren vind je op

2022-01-10 16:21 UTC, CathyDingemanse commented on docs/getting-started.md
> +- oas:generate-java-client (voor JAVA client code)
Deze repo bevat scripts waarmee je met behulp van [OpenAPI Generator](https://openapi-generator.tech/){:target="_blank" rel="noopener"} client code kan genereren in JAVA, .NET (Full Framework & Core) en Python. De makkelijkste manier om de code generatie scripts te gebruiken, is door deze repo te clonen. Na het clonen kun je met `npm install` de benodigde packages installeren. Vervolgens kun je met `npm run <script naam>` één van de volgende scripts worden uitvoeren:

2022-01-10 16:21 UTC, CathyDingemanse commented on docs/getting-started.md
> +
Een lijst met andere ondersteunde generator opties kun je vinden

2022-01-10 16:21 UTC, CathyDingemanse commented on docs/getting-started.md
> +
Je moet een JAVA runtime installeren voordat je OpenAPI Generator kunt gebruiken.

2022-01-19 08:02 UTC, JohanBoer approved these changes

2022-01-20 08:02 UTC, merged