Update verblijfplaats.yaml
VNG-Realisatie/Haal-Centraal-BRP-bevragen pull request #964
Opened 2022-03-15 08:19 UTC by melsk-r

N.a.v. het besluit om de straat, huisnummer, locatiebeschrijving en land van een verblijfplaats altijd op te vragen als een verblijfplaats wordt opgenomen in de fields parameter zijn deze properties verplicht gemaakt.

2022-03-15 10:17 UTC, fsamwel commented
Dit kan denk ik niet. Dit had gekund in de specifieke types Adres, Locatie en VerblijfBuitenland, maar niet in GbaVerblijfplaats. Deze 4 gegevens zijn namelijk nooit alle 4 tegelijk gevuld, ook niet met een standaardwaarde. Dus als er bijvoorbeeld een straat is, is er geen waarde voor locatie en geen waarde voor land. Dat zou betekenen dat geen enkele verblijfplaats geleverd kan worden.

Dit zouden we dan anders moeten oplossen. Bijvoorbeeld:
1. voor de 3 types elk een apart property met daarin de betreffende gegevens en de required properties
2. in de fields feature (#947) beschrijven dat deze altijd geleverd moeten worden wanneer er iets uit verblijfplaats gevraagd is
3. in de proxy-fields.feature (#959) beschrijven dat deze altijd gevraagd moeten worden

2022-03-15 10:17 UTC, fsamwel commented
Dit kan denk ik niet. Dit had gekund in de specifieke types Adres, Locatie en VerblijfBuitenland, maar niet in GbaVerblijfplaats. Deze 4 gegevens zijn namelijk nooit alle 4 tegelijk gevuld, ook niet met een standaardwaarde. Dus als er bijvoorbeeld een straat is, is er geen waarde voor locatie en geen waarde voor land. Dat zou betekenen dat geen enkele verblijfplaats geleverd kan worden.

Dit zouden we dan anders moeten oplossen. Bijvoorbeeld:
1. voor de 3 types elk een apart property met daarin de betreffende gegevens en de required properties
2. in de fields feature (#947) beschrijven dat deze altijd geleverd moeten worden wanneer er iets uit verblijfplaats gevraagd is
3. in de proxy-fields.feature (#959) beschrijven dat deze altijd gevraagd moeten worden

2022-03-15 12:35 UTC, melsk-r commented
Is het een optie om ook dit met polymorfisme op te lossen?

2022-03-15 14:19 UTC, fsamwel commented
> Is het een optie om ook dit met polymorfisme op te lossen?

Polymorfisme betekent dat de Gba variant een interpretatie doet van de verblijfplaatsgegevens en dat vertaalt naar een nieuw veld "type" waarin staat wat voor soort verblijfplaats het is. Dat zou dan een "informatievraag" zijn en dat mag juist niet.

2022-03-18 14:48 UTC, fsamwel requested changes
zoals in eerdere opmerking gezegd is het voor GbaVerblijfplaats niet mogelijk deze 4 velden te verplichten

2022-03-23 09:09 UTC, closed without merging