Wijzigingen van onbekend-naamgeving n.a.v. #958
VNG-Realisatie/Haal-Centraal-BRP-bevragen pull request #998
Opened 2022-04-08 11:06 UTC by JohanBoer

OnbekendDatum --> DatumOnbekend
OnbekendOuder --> OuderOnbekend
OnbekendKind --> KindOnbekend
OnbekendPartner --> PartnerOnbekend

Fixes #958

2022-04-11 08:36 UTC, MelvLee approved these changes

2022-04-14 09:29 UTC, fsamwel commented
onbekend dingen zitten ook in:
- fields.feature
- onbekend_waardes

2022-04-14 09:30 UTC, fsamwel requested changes
aanpassing ontbreekt nog in 2 features, verder prima

2022-04-14 11:56 UTC, JohanBoer commented
> aanpassing ontbreekt nog in 2 features, verder prima

Pak ik nog even mee. Deze zijn in een recente merge er bij gekomen. Zaten nog niet in develop toen ik mijn fork maakte.

2022-04-14 12:28 UTC, merged